command-line arguments for wallpaper script

diff --git a/.local/bin/wallpaper b/.local/bin/wallpaper
--- a/.local/bin/wallpaper
+++ b/.local/bin/wallpaper
@@ -4,8 +4,8 @@
 
 CACHE_FILE="$XDG_DATA_HOME/wallpaper-cache"
 CACHE_SIZE=10
+SIMULATE=0
 
-# TODO: add cache file option, cache size option, simulate run option
 # TODO: fix issue when cache is full and all files in folder are in it
 # TODO: make getwallpaper look pretty
 # TODO: make sure given file argument is image
@@ -42,13 +42,68 @@ getwallpaper() {
     cat "$CACHE_FILE"
 }
 
-while getopts "sgh" o; do
-    case "${o}" in
-        h) echo "Pass the directory to the wallpapers or any amount of files as parameters." && exit 1 ;;
-        g) getwallpaper && exit 0 ;;
-        s) setup && exit 0 ;;
+setup() {
+    if [ ! -f "$CACHE_FILE" ]; then
+        echo "Wallpaper cache file doesn't exist, creating..."
+        touch "$CACHE_FILE"
+    fi
+}
+
+isnum() {
+    case $1 in
+        ''|*[!0-9]*) return 1 ;;
+        *) return 0 ;;
     esac
+    return 1
+}
+
+isarg() {
+    case $1 in
+        -*|--*) return 0 ;;
+    esac
+    return 1
+}
+
+while (( "$#" )); do
+    case "$1" in
+        -h|--help)
+            echo "Pass the directory to the wallpapers or any amount of files as parameters."
+            exit 1 ;;
+        -g|--get)
+            getwallpaper
+            exit 0 ;;
+        --cache-file)
+            if ! isarg "$2"; then
+                CACHE_FILE="$2"
+                shift
+            else
+                echo "Cache file argument is required"
+                exit 1
+            fi ;;
+        --cache-size)
+            if isarg "$2"; then
+                echo "Cache file size argument is required"
+                exit 1
+            fi
+
+            if isnum "$2"; then
+               CACHE_SIZE="$2"
+               shift
+            else
+                echo "Cache file size argument is not an integer"
+                exit 1
+            fi ;;
+        --simulate)
+            SIMULATE=1 ;;
+        *)
+            if [ -e "$1" ]; then
+                break
+            fi ;;
+    esac
+    shift
 done
+
+# echo "$CACHE_FILE $CACHE_SIZE $SIMULATE"
 
 # if number of arguments is 0
 if [[ $# -eq 0 ]]; then
